# Generated by Django 4.1 on 2022-08-23 22:40

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='next_reminder',
            field=models.DateField(default=datetime.date(2022, 8, 23)),
            preserve_default=False,
        ),
    ]
