# Generated by Django 4.1 on 2022-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_friend_next_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
