# Generated by Django 4.1 on 2022-10-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_friend_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='stripe_customer_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
