# Generated by Django 4.1 on 2022-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userpreferences_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='stripe_customer_id',
            field=models.TextField(null=True, unique=True),
        ),
    ]
