# Generated by Django 4.1 on 2022-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userpreferences_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='subscription_status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Pending Payment', 'Pending Payment'), ('Active', 'Active')], default='Inactive', max_length=255),
        ),
    ]
